language: node_js
node_js:
  - lts/*

deploy:
  provider: npm
  email: alxlchnr@gmail.com
  api_key: ${API_TOKEN}
  script: "npm run release"
  skip_cleanup: true
  on:
    repo: alxlchnr/transitive-peerdeps
    branch: master
    condition: $TRAVIS_COMMIT_MESSAGE != /^chore\(release\)/

before_deploy:
  - npm run release

after_deploy:
  - git push --tags

notifications:
  email:
    recipients:
      - alxlchnr@gmail.com
    on_success: change
    on_failure: always