language: node_js
git:
  depth: false
node_js:
- lts/*
deploy:
  provider: npm
  email: alxlchnr@gmail.com
  api_key: "${API_TOKEN}"
  script: npm run release
  skip_cleanup: true
  on:
    repo: alxlchnr/transitive-peerdeps
    branch: master
    condition: "$TRAVIS_COMMIT_MESSAGE != /^chore\\(release\\)/"
before_deploy:
  - git config --global user.name "Travis CI"
  - git config --global user.email "alxlchnr@gmail.com"
  - npm run release
after_deploy:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git push -f -q https://${GITHUB_TOKEN}@github.com/alxlchnr/transitive-peerdeps.git master
  - git push --tags -q https://${GITHUB_TOKEN}@github.com/alxlchnr/transitive-peerdeps.git master
notifications:
  email:
    recipients:
      - alxlchnr@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    secure: SqX7U2+rYAf2MlMyqoBSp9WvDnHaR4qL5nQK6WCUz3Lqb54UeckAxSXdi4Y8NzOxOEG6gfijE6o6Y88uLK7yQx11ci2zeTMzMFW4lUUog0rGaLWBmc7uaSa5lG1uUM1XinO8Ll+MWmWkDZrGUQ4w2vI2E2mnNt7thAyiqzPAzPlp4b4ZYk9FYgm2vrUL2GnmIBQzj4OOEIbzn9eyb/6sd3U7pT2DIF7tACTc71iOuNtkj5YGPm+Knxei32NDiYtyaNnjaapy3GHUbDzaoxrtm1mo6GQRkuCIOfb9M3EU1DomIfinmnbH1QhEQNvf11Wkiv3EsIk8EzFxYa+3ORoRmF/ICpAjCf6wx5vZkgqlsmX7+rQCVHK2iZ8M8rFIG+8NwyqRKGmvzSxJK5bWRaOnOeYOzQNlT5pTVCy6FcfPVzpxeL8N8jBzxlfOh9E2Er6nF0KgfDrwaX3IrMldQ4EdP9PQVuXjTyKKpMgtq/eelp+US26gs4wcBuDgYV1Lp84JcRar3tmk/FnkYxvrrcfI0zxGrmnUyoeJgTkLNxlioJS8FsDsBMEDkwV9rhXEQhfEjisdQbfjWDqEUFvYr8UOJdpstFq9Kxl+oDiITZP1KzRazn8dl+KECFAjZVmD1V/WsGI0NWnmLyktj1HBc/1h+rYLkMvL7yiOI/bZ/udFS4U=
